language: node_js
node_js:
  - 10.15.1
cache: npm

install:
  - make ci

script: 
  - make predeploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: app/build
  on:
    branch: master