language: node_js
node_js:
  - "stable"
cache: npm

install:
  - npm ci

script: 
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN

on:
  branch: gh-pages

  
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: <my_name_here>.surge.sh
  project: ./build/
on:
  branch: master