language: node_js
node_js:
  - "stable"
cache: npm

before_install: 
  - cd app

install:
  - npm ci

script: 
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN

on:
  branch: gh-pages