language: node_js
node_js:
  - 10.15.1
cache: npm

before_install: 
  - cd app

install:
  - npm ci

script: 
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: app/build
  on:
    branch: master